import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#1c1c1c',
        paddingHorizontal: 20,
    },
    entryItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        backgroundColor: '#2a2a2a',
        borderRadius: 8,
        marginBottom: 10,
    },
    entryIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#333333',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    entryInfo: {
        flex: 1,
    },
    entryTitle: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    entryDate: {
        color: '#AAAAAA',
        fontSize: 12,
    },
    entryAmount: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    incomeAmount: {
        color: '#4CAF50',
    },
    expenseAmount: {
        color: '#F44336',
    },
    entryDescription: {
        color: '#AAAAAA',
        fontSize: 12,
        marginTop: 4,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#1c1c1c',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#1c1c1c',
    },
    emptyText: {
        color: '#AAAAAA',
        fontSize: 16,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        padding: 20,
    },
    modalContainer: {
        width: '80%',
        backgroundColor: '#2a2a2a',
        borderRadius: 10,
        padding: 20,
        borderWidth: 1,
        borderColor: '#D4AF37',
    },
    modalTitle: {
        color: '#D4AF37',
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 15,
        textAlign: 'center',
    },
    modalText: {
        color: '#FFFFFF',
        fontSize: 16,
        marginBottom: 20,
        textAlign: 'center',
    },
    modalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 15,
    },
    modalButton: {
        flex: 1,
        padding: 12,
        borderRadius: 6,
        marginHorizontal: 5,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
    },
    cancelButton: {
        backgroundColor: '#555555',
    },
    confirmButton: {
        backgroundColor: '#D4AF37',
    },
    deleteButton: {
        backgroundColor: '#d3ae37',
    },
    editButton: {
        backgroundColor: '#d3ae37',
    },
    modalButtonText: {
        color: '#000000',
        fontWeight: 'bold',
    },
    closeButton: {
        marginTop: 15,
        padding: 5,
        alignItems: 'center',
    },
    closeButtonText: {
        color: '#D4AF37',
        fontWeight: 'bold',
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
        paddingVertical: 5,
        borderBottomWidth: 1,
        borderBottomColor: '#333333',
    },
    detailLabel: {
        color: '#AAAAAA',
        fontSize: 14,
    },
    detailValue: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: 'bold',
    },
    tagsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 5,
    },
    tagPill: {
        borderRadius: 12,
        paddingVertical: 3,
        paddingHorizontal: 8,
        marginRight: 5,
        marginBottom: 5,
    },
    tagText: {
        color: '#FFFFFF',
        fontSize: 12,
    },
    entryCategory: {
        color: '#AAAAAA',
        fontSize: 12,
        marginTop: 2,
    },
    input: {
        backgroundColor: '#333333',
        borderRadius: 5,
        padding: 15,
        marginBottom: 15,
        color: '#FFFFFF',
        width: '100%',
    },
    dateInputContainer: {
        width: '100%',
        marginBottom: 15,
        marginTop: 0,
    },
    dateInput: {
        backgroundColor: '#333333',
        borderRadius: 5,
        padding: 15,
        marginBottom: 15,
        color: '#FFFFFF',
        width: '100%',
    },
    datePickerContainer: {
        position: 'relative',
        zIndex: 2,
        width: '100%',
    },
    dateInputContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    categoryContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 5,
    },
    categoryText: {
        color: '#D4AF37',
        fontSize: 14,
        marginLeft: 5,
    },
    tagsContainerModal: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 5,
        padding: 8,
        borderRadius: 5,
    },
    tagPillModal: {
        borderRadius: 12,
        paddingVertical: 5,
        paddingHorizontal: 10,
        marginRight: 5,
        marginBottom: 5,
        backgroundColor: '#333333',
    },
    tagTextModal: {
        color: '#FFFFFF',
        fontSize: 12,
    },
    detailDescriptionContainer: {
        marginBottom: 10,
        paddingVertical: 5,
        borderBottomWidth: 1,
        borderBottomColor: '#333333',
    },
    descriptionTextContainer: {
        marginTop: 5,
        padding: 8,
        borderRadius: 5,
    },
    detailTagsContainer: {
        marginBottom: 10,
        paddingVertical: 5,
        borderBottomWidth: 1,
        borderBottomColor: '#333333',
    },
    fullScreenModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'flex-end',
    },
    fullScreenModalContainer: {
        backgroundColor: '#1c1c1c',
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        maxHeight: '75%',
        height: '75%',
        width: '100%',
        flex: 1,
        overflow: 'hidden',
    },
    editModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#333333',
    },
    editModalTitle: {
        color: '#D4AF37',
        fontSize: 18,
        fontWeight: 'bold',
    },
    editModalCloseButton: {
        padding: 5,
        marginLeft: 10,
    },
    datePickerWrapper: {
        position: 'absolute',
        top: 60,
        left: 0,
        right: 0,
        zIndex: 100,
        backgroundColor: '#2a2a2a',
        borderRadius: 10,
        elevation: 5,
    },
    datePickerButton: {
        backgroundColor: '#D4AF37',
        padding: 10,
        borderRadius: 5,
        alignItems: 'center',
        marginBottom: 15,
    },
    datePickerButtonText: {
        color: '#000000',
        fontWeight: 'bold',
    },
});

export default styles;
