export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  isRead: boolean;
  data?: any;
  createdAt: string;
  updatedAt: string;
}

export enum NotificationType {
  APPOINTMENT_REQUEST = 'APPOINTMENT_REQUEST',
  APPOINTMENT_REQUEST_ACCEPTED = 'APPOINTMENT_REQUEST_ACCEPTED',
  APPOINTMENT_RESCHEDULED_BY_USER = 'APPOINTMENT_RESCHEDULED_BY_USER',
  APPOINTMENT_RESCHEDULED_BY_ADMIN = 'APPOINTMENT_RESCHEDULED_BY_ADMIN',
  APPOINTMENT_RESCHEDULE_ACCEPTED = 'APPOINTMENT_RESCHEDULE_ACCEPTED',
  APPOINTMENT_RESCHEDULE_COUNTER_PROPOSAL = 'APPOINTMENT_RESCHEDULE_COUNTER_PROPOSAL',
  APPOINTMENT_RESCHEDULE_COUNTER_CONFIRMED = 'APPOINTMENT_RESCHEDULE_COUNTER_CONFIRMED',
  APPOINTMENT_RESCHEDULE_COUNTER_REJECTED = 'APPOINTMENT_RESCHEDULE_COUNTER_REJECTED',
  APPOINTMENT_RESCHEDULE_REJECTED = 'APPOINTMENT_RESCHEDULE_REJECTED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_CANCELLED_BY_ADMIN = 'APPOINTMENT_CANCELLED_BY_ADMIN',
  APPOINTMENT_PENDING_REVIEW = 'APPOINTMENT_PENDING_REVIEW',
  PENDING_APPOINTMENTS_REMINDER = 'PENDING_APPOINTMENTS_REMINDER',
  PROFILE_INCOMPLETE = 'PROFILE_INCOMPLETE',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
}

export interface NotificationsResponse {
  notifications: Notification[];
  totalCount: number;
  unreadCount: number;
  currentPage: number;
  totalPages: number;
}

export interface UnreadCountResponse {
  unreadCount: number;
}
