import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        paddingHorizontal: 30,
        paddingTop: 50,
        paddingBottom: 20,
        backgroundColor: '#121212',
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: 40,
    },
    logo: {
        width: 140,
        height: 140,
        marginBottom: 25,
    },
    title: {
        fontSize: 24,
        fontWeight: '600',
        marginBottom: 30,
        textAlign: 'center',
        color: '#D4AF37',
            fontFamily: 'sans-serif',
        letterSpacing: 0.8,
        textShadowColor: 'rgba(212, 175, 55, 0.4)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
    inputContainer: {
        marginBottom: 18,
    },
    input: {
        height: 52,
        borderColor: '#D4AF37',
        borderWidth: 1.5,
        borderRadius: 10,
        paddingHorizontal: 18,
        backgroundColor: 'rgba(212, 175, 55, 0.08)',
        fontSize: 16,
        color: '#FFFFFF',
        shadowColor: '#D4AF37',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3,
        elevation: 4,
    },
    button: {
        backgroundColor: '#D4AF37',
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
        flexDirection: 'row',
        shadowColor: '#D4AF37',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 7,
    },
    disabledButton: {
        opacity: 0.7,
        backgroundColor: 'rgba(212, 175, 55, 0.6)',
    },
    buttonText: {
        color: '#000000',
        fontSize: 17,
        fontWeight: '600',
        letterSpacing: 0.8,
        marginLeft: 10,
    },
    linkText: {
        marginTop: 25,
        textAlign: 'center',
        color: '#D4AF37',
        fontSize: 15,
        fontWeight: '500',
    },
    linkBold: {
        fontWeight: '700',
        textDecorationLine: 'underline',
    },
    errorText: {
        color: '#FF5555',
        textAlign: 'center',
        marginBottom: 18,
        fontSize: 14,
        backgroundColor: 'rgba(255, 85, 85, 0.12)',
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255, 85, 85, 0.25)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 28,
    },
    dividerLine: {
        flex: 1,
        height: 1.2,
        backgroundColor: 'rgba(212, 175, 55, 0.3)',
    },
    dividerText: {
        marginHorizontal: 12,
        color: '#D4AF37',
        fontSize: 14,
        fontWeight: '500',
        letterSpacing: 0.5,
    },
    socialButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 15,
        marginBottom: 25,
    },
    socialButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        borderWidth: 1.2,
        borderColor: '#D4AF37',
        marginHorizontal: 10,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(212, 175, 55, 0.1)',
    },
    socialButtonText: {
        marginLeft: 8,
        fontSize: 15,
        fontWeight: '600',
        color: '#D4AF37',
    },
    registerLink: {
        marginTop: 15,
    },
    iconContainer: {
        marginRight: 8,
    },
    forgotPasswordLink: {
        alignSelf: 'flex-end',
        marginBottom: 15,
    },
    forgotPasswordText: {
        color: '#D4AF37',
        fontSize: 14,
        textDecorationLine: 'underline',
    },
});
