import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 30,
        paddingVertical: 20,
        backgroundColor: '#1c1c1c',
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: 20,
    },
    logo: {
        width: 120,
        height: 120,
        marginBottom: 20,
    },

    titleContainer: {
        alignItems: 'center',
        marginBottom: 20,
    },
    title: {
        fontSize: 26,
        fontWeight: '600',
        marginBottom: 15,
        textAlign: 'center',
        color: '#D4AF37',
        fontFamily: 'sans-serif',
        letterSpacing: 0.5,
        textShadowColor: 'rgba(212, 175, 55, 0.5)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 4,
    },
    inputContainer: {
        marginBottom: 15,
    },
    input: {
        height: 50,
        borderColor: '#D4AF37',
        borderWidth: 1.5,
        borderRadius: 8,
        paddingHorizontal: 15,
        backgroundColor: 'rgba(212, 175, 55, 0.08)',
        fontSize: 16,
        color: '#FFFFFF',
        shadowColor: '#D4AF37',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    inputError: {
        borderColor: '#FF5555',
        backgroundColor: 'rgba(255, 85, 85, 0.08)',
    },
    countryInput: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        height: 50,
        borderColor: '#D4AF37',
        borderWidth: 1.5,
        borderRadius: 8,
        paddingHorizontal: 15,
        backgroundColor: 'rgba(212, 175, 55, 0.08)',
    },
    countrySelectedText: {
        fontSize: 16,
        color: '#FFFFFF',
        flex: 1,
    },
    placeholderText: {
        fontSize: 16,
        color: '#555555',
        flex: 1,
    },
    button: {
        backgroundColor: '#D4AF37',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 15,
        flexDirection: 'row',
        shadowColor: '#D4AF37',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 6,
    },
    disabledButton: {
        opacity: 0.7,
        backgroundColor: 'rgba(212, 175, 55, 0.7)',
    },
    buttonText: {
        color: '#000000',
        fontSize: 17,
        fontWeight: '600',
        letterSpacing: 0.5,
        marginLeft: 8,
    },
    loginLinkContainer: {
        marginTop: 20,
    },
    loginText: {
        textAlign: 'center',
        color: '#D4AF37',
        fontSize: 15,
    },
    loginLink: {
        fontWeight: '700',
        textDecorationLine: 'underline',
    },
    errorText: {
        color: '#FF5555',
        textAlign: 'center',
        marginBottom: 15,
        fontSize: 14,
        backgroundColor: 'rgba(255, 85, 85, 0.1)',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: 'rgba(255, 85, 85, 0.3)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalPickerContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#2a2a2a',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        maxHeight: '60%',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#333',
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        height: 40,
        color: '#FFFFFF',
        fontSize: 16,
    },
    countryList: {
        maxHeight: '80%',
    },
    countryItem: {
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#333',
    },
    countryItemText: {
        color: '#FFFFFF',
        fontSize: 16,
    },
});
